### ISSUE TITLE
Странный краш от Хромы

### ISSUE THREAD

**Issue by Gargule** [MaintainersOfMine1-7-10/MinecraftModpack1710#2]
Она почему-то крашит при первом старте. Хз в чём дело.

**Comment by Gargule** [comment]
На случай, если что-то забредёт в эту помойку и захочет помочь. (Да-да, потвикать другие моды и их версии. Я не буду этого делать)
```
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: Could not initialize class Reika.ChromatiCraft.Magic.Progression.ResearchLevel
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
```
Список модов можно увидеть в папке модов.
